# Generated by Django 3.2.16 on 2023-01-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weather_records',
            fields=[
                ('dates', models.DateField(primary_key=True, serialize=False)),
                ('Max_temp', models.IntegerField()),
                ('Min_temp', models.IntegerField()),
                ('Precipitation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='yield_records',
            fields=[
                ('yield_year', models.IntegerField(primary_key=True, serialize=False)),
                ('yield_data', models.IntegerField()),
            ],
        ),
    ]
