# Generated by Django 3.2.16 on 2023-01-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='Max_temp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Min_temp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Precipitation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
