# Generated by Django 3.2.16 on 2023-01-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_auto_20230119_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='result1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('Min_temp', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='result2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='result',
            name='Min_temp',
        ),
        migrations.RemoveField(
            model_name='result',
            name='Precipitation',
        ),
    ]
